spring:
  datasource:
    url: jdbc:sqlite:/urls
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.beinet.shorturl.sqlite.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
